### ISSUE TITLE
node-apex v2 keeps timing out

### ISSUE THREAD

**Issue by schickling** [apex/node-apex#6]
Since the version bump to v2 introducing the `cb` method, my lambda functions keep timing out. I've downgraded to v1 for now.

Any ideas? @ajcrites

**Comment by ajcrites** [comment]
Can you create an SSCCE that represents the function?

**Comment by schickling** [comment]
Sure. Here's a quick example:

``` json
{
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015",
            "stage-0"
          ],
          "plugins": [
            "transform-runtime"
          ]
        }
      ]
    ]
  },
  "scripts": {
    "build": "mkdir -p dist && browserify --node -s default -x aws-sdk -o dist/index.js index.js"
  },
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babelify": "^7.2.0",
    "browserify": "^13.0.0"
  },
  "dependencies": {
    "apex.js": "^2.0.0"
  }
}
```

``` js
import apex from 'apex.js'

export default apex(async(e) => {
  await doAsyncStuff()
})
```

**Comment by ebourmalo** [comment]
Same for us, since we updated to Apex.js 2.0.0, functions keep timing out =/

**Comment by ebourmalo** [comment]
After some investigation, I think it's due to the setting `callbackWaitsForEmptyEventLoop` available from the context object: http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

I'll do my tests soon and get back to you

Edit: I updated this setting on my fork to make it work without having any timeout: https://github.com/ebourmalo/node-apex/blob/master/index.js#L6

**Comment by tj** [comment]
haha nice of them to add breaking changes

**Comment by ebourmalo** [comment]
@tj Should i propose a PR for that or do you stick to the default behaviour?

**Comment by ajcrites** [comment]
@ebourmalo I would just leave this with the default behavior, but since you have access to the context you can set `callbackWaitsForEmptyEventLoop = false` in the lambda itself if you want this behavior.

I would recommend against this behavior personally. The better question might be why your event loop is not emptying.

**Comment by tj** [comment]
It's pretty common to have a connection pool etc, I think it would be a sane to disable it by default, especially in the shim as well

**Comment by tj** [comment]
Nevermind I take that back, node defaults should just be whatever Lambda defaults are but it'll have to be fixed in the shim

**Comment by ajcrites** [comment]
@tj I think this can be done in the lambda function itself when you pass in `ctx`, i.e. this can be done without changes to the library.

**Comment by tj** [comment]
Yeah it's fine for this lib, I'll close for now. The shim would need it disabled I believe, since the child process and pipe would be open, but that's a different issue.
